In [70]:
import numpy as np
# write everything from scratch

# below we have the empty density matrix
p = np.matrix('0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0') 

max_entropy = np.matrix('0.5,0;0,0.5')
# coefficients of each of the eight basis elements in order
c = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
state_list = []
number_states = 0
l0 = -1.0
while l0 < 2.0:
    c[0] = float(l0)
    l1 = -1.0
    while l1 < 2.0:
        c[1] = float(l1)
        l2 = -1.0
        while l2 < 2.0:
            c[2] = float(l2)
            l3 = -1.0
            while l3 < 2.0:
                c[3] = float(l3)
                l4 = -1.0
                while l4 < 2.0:
                    c[4] = float(l4)
                    l5 = -1.0
                    while l5 < 2.0:
                        c[5] = float(l5)
                        l6 = -1.0
                        while l6 < 2.0:
                            c[6] = float(l6)
                            l7 = -1.0
                            while l7 < 2.0:
                                c[7] = float(l7)
                                vector = [c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]]

                                i = 0
                                while i < 8:  # constructing density matrix
                                    j = 0
                                    while j < 8:
                                        p[i,j] = vector[i] *vector[j]
                                        j = j + 1
                                    i = i + 1   

                                k = 0
                                norm = 8.0
                                while k < 8.0:
                                    if c[k] == 0:
                                        norm = norm - 1
                                    k = k + 1     

                                #partial trace A
                                
                                a_tr = np.matrix('0.0 0.0 ; 0.0 0.0')
                                a_tr[0,0] = (p[0,0] + p[1,1] + p[2,2] + p[3,3])/norm
                                a_tr[0,1] = (p[0,4] + p[1,5] + p[2,6] + p[3,7])/norm
                                a_tr[1,0] = (p[4,0] + p[5,1] + p[6,2] + p[7,3])/norm
                                a_tr[1,1] = (p[4,4] + p[5,5] + p[6,6] + p[7,7])/norm
                                
                                #partial trace B
                                
                                b_tr = np.matrix('0.0 0.0 ; 0.0 0.0')
                                b_tr[0,0] = (p[0,0] + p[1,1] + p[4,4] + p[5,5])/norm
                                b_tr[0,1] = (p[0,2] + p[1,3] + p[4,6] + p[5,7])/norm
                                b_tr[1,0] = (p[2,0] + p[3,1] + p[6,4] + p[7,5])/norm
                                b_tr[1,1] = (p[2,2] + p[3,3] + p[6,6] + p[7,7])/norm
                                
                                #partial trace C
                                
                                c_tr = np.matrix('0.0 0.0 ; 0.0 0.0')
                                c_tr[0,0] = (p[0,0] + p[2,2] + p[4,4] + p[6,6])/norm
                                c_tr[0,1] = (p[0,1] + p[2,3] + p[4,5] + p[6,7])/norm
                                c_tr[1,0] = (p[1,0] + p[3,2] + p[5,4] + p[7,6])/norm
                                c_tr[1,1] = (p[1,1] + p[3,3] + p[5,5] + p[7,7])/norm
                                
                                if a_tr[0,0] == max_entropy[0,0]:
                                    
                                    if a_tr[0,1] == max_entropy[0,1]:
                                        if a_tr[1,0] == max_entropy[1,0]:
                                            if a_tr[1,1] == max_entropy[1,1]:
                                                if b_tr[0,0] == max_entropy[0,0]:
                                                    if b_tr[0,1] == max_entropy[0,1]:
                                                        if b_tr[1,0] == max_entropy[1,0]:
                                                            if b_tr[1,1] == max_entropy[1,1]:
                                                                if c_tr[0,0] == max_entropy[0,0]:
                                                                    if c_tr[0,1] == max_entropy[0,1]:
                                                                        if c_tr[1,0] == max_entropy[1,0]:
                                                                            if c_tr[1,1] == max_entropy[1,1]:
                                                                                number_states = number_states + 1
                                                                                state_list.append(vector)
                                                                                #print(vector)
                                                                                #print(a_tr)
                                                                                #print(b_tr)
                                                                                #print(c_tr)
                                                
                                                
                                
                                l7 = l7 + 1.0
                            l6 = l6 + 1.0
                        l5 = l5 + 1.0
                    l4 = l4 + 1.0
                l3 = l3 + 1.0
            l2 = l2 + 1.0
        l1 = l1 + 1.0
    l0 = l0 + 1.0
                                

#print(number_states)






[-1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0]
[-1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0]
[-1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0]
[-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0]
[-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0]
[-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0]
[-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0]
[-1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0]
[-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0]
[-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -1.0]
[-1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0]
[-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0]
[-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0]
[-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0]
[-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0]
[-1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0]
[-1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0]
[-1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0]
[-1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 1.0]
[-1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 0.0, -1.0]
[-1.0, 0.0, 0.0, -1.0, -1.0, 0.0, 0.0, 1.0]
[-1.0, 0.0, 0.0, -1.0, 0.0, -1.0, -1.0, 0.0]

C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:56: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:57: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:58: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:59: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:64: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:65: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:66: RuntimeWarning: invalid value encountered in true_divide
C:\Users\Sudevan\Anaconda3\lib\site-packages\ipykernel_launcher.py:67: RuntimeWarning: invalid value enc

[0.0, 0.0, 0.0, 1.0, -1.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 1.0, -1.0, -1.0, -1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, -1.0, 1.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 0.0, 0.0, -1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 1.0, -1.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 1.0, 1.0, 1.0, -1.0, 0.0, 0.0]
[0.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, -1.0]
[0.0, 1.0, -1.0, 0.0, -1.0, 0.0, 0.0, 1.0]
[0.0, 1.0, -1.0, 0.0, 0.0, -1.0, -1.0, 0.0]
[0.0, 1.0, -1.0, 0.0, 0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, -1.0, 0.0, 1.0, 0.0, 0.0, -1.0]
[0.0, 1.0, -1.0, 0.0, 1.0, 0.0, 0.0, 1.0]
[0.0, 1.0, 0.0, -1.0, -1.0, 0.0, -1.0, 0.0]
[0.0, 1.0, 0.0, -1.0, 1.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 1.0, -1.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 1.0, 1.0, 0.0, -1.0, 0.0]
[0.0, 1.0, 1.0, 0.0, -1.0, 0.0, 0.0, -1.0]
[0.0, 1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0]
[0.0, 1.0, 1.0, 0.0, 0.0, -1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 0.0, 0.0, 

In [71]:
#print(number_states)
#len(state_list)
#print(state_list)

[[-1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0], [-1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0], [-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0], [-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0], [-1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0], [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0], [-1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 1.0], [-1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 0.0, -1.0], [-1.0, 0.0, 0.0, -1.0, -1.0, 0.0, 0.0, 1.0], [-1.0, 0.0, 0.0, -1.0,

In [72]:
# removing half the states, the ones that are just negative of the others

i = 0
while i < len(state_list):
    j = 0
    temp = np.dot(state_list[i],-1)
    
    while j < len(state_list):
        count = 0
        del_counter = 0
        while count < 8:
            if temp[count] == state_list[j][count]:
                del_counter = del_counter + 1
            count = count + 1
        if del_counter == 8:
            del state_list[j]
        j = j + 1
    i = i + 1

print(state_list)
print(len(state_list))
        
       
        
            
        

[[-1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0], [-1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0], [-1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0], [-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0], [-1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0], [-1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0], [-1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0], [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0], [-1.0, 0.0, -1.0, 0.0, 0.0, -1.0, 0.0, 1.0], [-1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 0.0, -1.0], [-1.0, 0.0, 0.0, -1.0, -1.0, 0.0, 0.0, 1.0], [-1.0, 0.0, 0.0, -1.0,

In [73]:
# finding mutually orthonormal sets of vectors

ortho = state_list

count = 0

while count < len(ortho):
    
    
    count2 = 0
    while count2 < len(ortho):
        if count2 !=count:
            
            if np.dot(ortho[count],ortho[count2]) != 0:
                del ortho[count2] 
            else:
                count2 = count2 + 1
        else:
            count2 = count2 + 1
        
    count = count + 1

    





In [80]:
count = 0
while count < len(ortho):
    print(count + 1)
    
    print(ortho[count])
    
    print("woop woop")
    count = count + 1

1
[-1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0]
woop woop
2
[-1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0]
woop woop
3
[-1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0]
woop woop
4
[-1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0]
woop woop
5
[-1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0]
woop woop
6
[-1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0]
woop woop
7
[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
woop woop
8
[-1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0]
woop woop


In [77]:
# Constructing the hamiltonian
# we first write code for tensor product

H = np.matrix('0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0')
tensor_sum = np.matrix('0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0')
count = 0
while count < 8:
 # constructing projection operator   
    i = 0
    while i < 8:
        j = 0
        while j < 8:
            test = ortho[count]
            tensor_sum[i,j] = test[i]*test[j]
            j = j + 1
        i = i + 1
    
    
    print(count)
    print(tensor_sum)
    print("woop woop")
    # code for adding two matrices
    i = 0
    while i < 8:
        j = 0
        while j < 8:
            H[i,j] = H[i,j] + tensor_sum[i,j]
            j = j + 1
        i = i + 1
    print(H)
    count = count + 1
      

0
[[ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [-1 -1 -1 -1 -1  1  1 -1]
 [-1 -1 -1 -1 -1  1  1 -1]
 [ 1  1  1  1  1 -1 -1  1]]
woop woop
[[ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1  1 -1 -1  1]
 [-1 -1 -1 -1 -1  1  1 -1]
 [-1 -1 -1 -1 -1  1  1 -1]
 [ 1  1  1  1  1 -1 -1  1]]
1
[[ 1  1  1  1 -1  1  1 -1]
 [ 1  1  1  1 -1  1  1 -1]
 [ 1  1  1  1 -1  1  1 -1]
 [ 1  1  1  1 -1  1  1 -1]
 [-1 -1 -1 -1  1 -1 -1  1]
 [ 1  1  1  1 -1  1  1 -1]
 [ 1  1  1  1 -1  1  1 -1]
 [-1 -1 -1 -1  1 -1 -1  1]]
woop woop
[[ 2  2  2  2  0  0  0  0]
 [ 2  2  2  2  0  0  0  0]
 [ 2  2  2  2  0  0  0  0]
 [ 2  2  2  2  0  0  0  0]
 [ 0  0  0  0  2 -2 -2  2]
 [ 0  0  0  0 -2  2  2 -2]
 [ 0  0  0  0 -2  2  2 -2]
 [ 0  0  0  0  2 -2 -2  2]]
2
[[ 1  1 -1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1 -1  1 -1]
 [-1 -1  1  1 -1  1 -1  1]
 [-1 -1  1  1 -1  1 -1  1

In [78]:
#below we have the hamiltonian, each entry has to be divided by 8 since I did not normalize the vectors
print(H)


[[8 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0]
 [0 0 0 8 0 0 0 0]
 [0 0 0 0 8 0 0 0]
 [0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 8]]


In [65]:
test1 = np.matrix('1,3;7,0')
test2 = np.matrix('2,4;3,2')
test3 = test1 + test2
print(test3)

[[ 3  7]
 [10  2]]


2
